### ISSUE TITLE
[BUG] Getting the error AttributeError: 'NoneType' object has no attribute 'groups' while adding vpc and subnets

### ISSUE THREAD

**Issue by chughrahul** [compose-x/ecs_composex#730] opened 2023-12-14 12:37 UTC
The error says -
```
2023-12-14 18:04:42 [INFO], Matched ec2:vpc to AWS Resource
2023-12-14 18:04:43 [INFO], Matched ec2:subnet to AWS Resource
Traceback (most recent call last):
  File "/Users/rahulchugh/Documents/venv/bin/ecs-compose-x", line 8, in <module>
    sys.exit(main())
  File "/Users/rahulchugh/Documents/venv/lib/python3.6/site-packages/ecs_composex/cli.py", line 166, in main
    root_stack = generate_full_template(settings)
  File "/Users/rahulchugh/Documents/venv/lib/python3.6/site-packages/ecs_composex/ecs_composex.py", line 324, in generate_full_template
    vpc_stack = add_vpc_to_root(root_stack, settings)
  File "/Users/rahulchugh/Documents/venv/lib/python3.6/site-packages/ecs_composex/vpc/vpc_stack.py", line 255, in add_vpc_to_root
    settings.compose_content[vpc_xkey]["Lookup"], settings.session
  File "/Users/rahulchugh/Documents/venv/lib/python3.6/site-packages/ecs_composex/vpc/vpc_aws.py", line 79, in lookup_x_vpc_settings
    for subnet_arn in subnet_arns
  File "/Users/rahulchugh/Documents/venv/lib/python3.6/site-packages/ecs_composex/vpc/vpc_aws.py", line 79, in <listcomp>
    for subnet_arn in subnet_arns
AttributeError: 'NoneType' object has no attribute 'groups'
```

And the x-vpc section in my docker compose is-
```
x-vpc:
  Lookup:
    VpcId:
      Tags:
        - Name: My-Backend-VPC
    PublicSubnets:
      Tags:
        - Name: public-My-Backend-1
    AppSubnets:
      Tags:
        - Name: private-My-Backend-1
    StorageSubnets:
      Tags:
        - Name: private-My-Backend-2
```
I've my VPC and subnets with the same name but the lookup giving this error. What can be the reason behind this?

**Comment by chughrahul** [comment] 2023-12-15 03:46
Hi @JohnPreston 
Here are the tags on my VPC and subnets -

VPC-
```
Name - My-Backend-VPC
aws:cloudformation:stack-id - arn:aws:cloudformation:ap-south-1:<ID>
aws:cloudformation:stack-name - EC2ContainerService-My-Backend
aws:cloudformation:logical-id - Vpc
```
Subnets-
```
1-
aws:cloudformation:stack-id - arn:aws:cloudformation:ap-south-1:<ID>
aws:cloudformation:logical-id - PubSubnetAz1
Name | public-My-Backend-1
aws:cloudformation:stack-name | EC2ContainerService-My-Backend

2-
Name - private-My-Backend-1

3-
Name - private-My-Backend-2
```


Do I need to add more tags to my subnets or VPC to get it working?

**Comment by JohnPreston** [comment] 2023-12-15 07:08
No that should be all fine.
Will have a look and open a fix branch in a bit

**Comment by JohnPreston** [comment] 2023-12-15 07:24
@chughrahul I just noticed from your logs that you are using Python 3.6 which has reached end of life.
Can you confirm for me please the compose-x version then? I never thought of that, but given compose-x min required version is above 3.6, I wonder if pip installed the "latest" compose-x version which was supported with python 3.6.

It seems to me that, it would be the case, given that line 79 of the latest code does not do anything at all what's in your logs.

If you are on a system and you cannot update the python version to, say at least 3.10, I'd recommend to try using the [docker image](https://gallery.ecr.aws/compose-x/compose-x) instead.

**Comment by chughrahul** [comment] 2023-12-17 12:05
Yes I think that was a problem. Thanks for the solution it worked.

I'm trying to deploy it to aws ecs. The services are getting added but they're using the existing images on ecr and not uploading a new image to ecr. Can you please share the steps so that it pushes a new image to ecr every time and use that to deploy the services?

**Comment by JohnPreston** [comment] 2023-12-18 07:50
The best practice would be to build and push your image to AWS ECR via CICD (GH Action, or my fav, CodePipeline + CodeBuild, etc.), then run ecs-compose-x

[This](https://github.com/compose-x/codepipline-orchestra/blob/main/app-pipeline-boilerplate/%7B%7Bcookiecutter.repository_name%7Clower%7D%7D/cicd/buildspec.yml#L35-L47) is an example with a very simplifed version of how we build and deploy our java apps.

Otherwise, from your machine, just run to build and push the image(s). Make sure to set `image` in your services to the right repository.

```bash
docker compose build
docker compose push
ecs-compose-x <command>
```

**Comment by JohnPreston** [comment] 2023-12-18 07:51
Closing as this is not a bug per say. Feel free to correspond here @chughrahul or join the [Slack Channel](https://join.slack.com/t/compose-x/shared_invite/zt-w9ly4f3k-QhqGDs57RY7WcBnLYDw_lg)

**Closed by JohnPreston** 2023-12-18 07:51 UTC
Labels: bug
